server:
    port: 8095
spring:
    application:
        name: service-server

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
    client:
        serviceUrl:
            defaultZone: http://localhost:9999/eureka/
