server:
    port: 1111
spring:
    application:
        name: service-gateway

# ZUUL (Load balancing)
zuul:
    ignoredServices: '*'
    routes:
        service-server:
            stripPrefix: true
            path: /api/**
            serviceId:  SERVICE-SERVER


# EUREKA (Service registry)
eureka:
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
    client:
        serviceUrl:
            defaultZone: http://localhost:9999/eureka/